### ISSUE TITLE
MessageBox window is truncated

### ISSUE THREAD

**Issue by ericbrunner** [AvaloniaUtils/MessageBox.Avalonia#61] opened 2021-04-21 06:02 UTC
Since `v. 1.1.2` MessageBox window is truncated.

SetupCode:

```
public static Task ShowDialog(string message, Icon icon = Icon.Info,
            DispatcherPriority priority = DispatcherPriority.Normal, Window? parentWindow = null)
        {
            return Dispatcher.UIThread.InvokeAsync(async () =>
            {
                var messageBoxParams = new MessageBoxStandardParams()
                {
                    CanResize = true,
                    ContentTitle = "Sunify UI",
                    ContentMessage =
                        $"{message}. Please take a look in logs folder and contact the admin from SUNIFY for further support.",
                    Icon = icon,
                    ButtonDefinitions = ButtonEnum.Ok,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    Style = GetDialogStyle()
                };
                var messageBoxStandardWindow = MessageBox.Avalonia.MessageBoxManager
                    .GetMessageBoxStandardWindow(messageBoxParams);

                await messageBoxStandardWindow.Show(parentWindow ?? MainWindow);
            }, priority);
        }

        private static Style GetDialogStyle()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) return Style.UbuntuLinux;
            return RuntimeInformation.IsOSPlatform(OSPlatform.OSX) ? Style.MacOs : Style.Windows;
        }
```

Result:

![image](https://user-images.githubusercontent.com/6480047/115504180-d13a5100-a277-11eb-84c3-dbe9ca715414.png)

**Comment by alessandrofrancesconi** [comment] 2021-04-21 09:34
Duplicate of #52

**Closed** 2021-04-22 08:32 UTC
